name: Java Tests # Tests and pushes to unstable

on: 
  push:
    branches: "**" # Runs on all branches but never on tags
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Timestamp
        id: time
        uses: 1466587594/get-current-time@v2
        with:
          format: ${[GITHUB_RUN_NUMBER]}, MMM. D, YYYY [Unstable] # Pulls the tag name and current date to produce clientVersion > v1.0.0, Jan. 1, 1970

      - name: Run Tests
        run: |
          echo "COMMIT=${GITHUB_SHA::8}" >> $GITHUB_ENV
          export PATH=./tools:$PATH
          chmod +x ./tools/antialias
          ./gradlew test desktop:dist -PupdateUrl=${{ github.repository }}-builds -PclientVersion="${{ steps.time.outputs.formattedTime }}" --parallel -PfastAA

      - name: Create Release
        if: ${{ github.repository == 'mindustry-antigrief/mindustry-client-v6' && (github.ref == 'refs/heads/custom-client' || github.event_name == 'workflow_dispatch') }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          body: |
            Foo's Client Unstable ${{ github.run_number }} (${{ env.COMMIT }})
            Steam installation instructions [here](../../../mindustry-client-v6#steam)
            **Commit Message:**
            *${{ github.event.head_commit.message }}*
          commitish: main
          tag_name: ${{ github.run_number }}
          release_name: Unstable ${{ github.run_number }} (${{ env.COMMIT }})
          repo: ${{ github.event.repository.name }}-builds
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: ${{ github.repository == 'mindustry-antigrief/mindustry-client-v6' && (github.ref == 'refs/heads/custom-client' || github.event_name == 'workflow_dispatch') }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: desktop/build/libs/Mindustry.jar
          asset_name: desktop.jar
          asset_content_type: application/zip

      - name: Upload Artifact (No release was made)
        if: ${{ !(github.repository == 'mindustry-antigrief/mindustry-client-v6' && (github.ref == 'refs/heads/custom-client' || github.event_name == 'workflow_dispatch')) }}
        uses: actions/upload-artifact@v2
        with:
          name: Desktop JAR (zipped)
          path: desktop/build/libs/Mindustry.jar

      - name: Upload Test Results To Pages
        if: ${{ !cancelled() && github.repository == 'mindustry-antigrief/mindustry-client-v6' && (github.ref == 'refs/heads/custom-client' || github.event_name == 'workflow_dispatch') }}
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          repository-name: ${{ github.repository }}-builds
          branch: gh-pages # The branch the action should deploy to.
          folder: tests/build/reports/tests/test
          silent: true
          single-commit: true
